encryptme/encryption/urls.py
from django.urls import path

from . import views

app_name = 'encryption'
urlpatterns = [
    path('', views.index, name='index'),
    path('caesar/', views.caesar, name='caesar'),
    path('vernam/', views.vernam, name='vernam'),
    path('vigenere/', views.vigenere, name='vigenere'),
    path('encrypt_vernam', views.encrypt_vernam, name='encrypt_vernam'),
    path('decrypt_vernam', views.decrypt_vernam, name='decrypt_vernam'),
    path('encrypt_vigenere', views.encrypt_vigenere, name='encrypt_vigenere'),
    path('decrypt_vigenere', views.decrypt_vigenere, name='decrypt_vigenere'),
    path('encrypt_decrypt_caesar', views.encrypt_decrypt_caesar, name='encrypt_decrypt_caesar')
]

encryptme/encryptme/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('encryption.urls')),
    path('admin/', admin.site.urls),
]

encryptme/encryption/models.py
import datetime

from django.db import models
from django.db.models.base import Model
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    @admin.display(
            boolean=True,
            ordering='pub_date',
            description='Published recently?',
        )

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

encryptme/encryption/views.py
from django import template
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt

from .models import Choice, Question
from .vernam import vernam_cipher, vernam_cipher_decoder
from .caesar import caesar_cipher
from .vigenere import vigenere_cipher, vigenere_cipher_decoder

def index(request):
    return render(request, 'encryption/index.html')

def caesar(request):
    return render(request, 'encryption/caesar.html')

def vernam(request):
    return render(request, 'encryption/vernam.html')

def vigenere(request):
    return render(request, 'encryption/vigenere.html')

def get_params(request):
    text = request.POST['to_encrypt']
    key = request.POST['key']
    return text, key

def check_string(s):
    s = s.strip()
    s = s.replace(" ", "")
    s = " ".join(s.split())
    return s

def encrypt_vernam(request):
    if request.method == "POST":
        text, key = get_params(request)
        if (not key.isspace()) and (key.isalpha()):
            en_text = vernam_cipher(text, key)
        else:
            en_text = "Invalid key."
        return HttpResponse(en_text)

def decrypt_vernam(request):
    if request.method == "POST":
        text, key = get_params(request)
        if (not key.isspace()) and (key.isalpha()):
            en_text = vernam_cipher_decoder(text, key)
        else:
            en_text = "Invalid key."
        return HttpResponse(en_text)

def encrypt_vigenere(request):
    if request.method == "POST":
        text, key = get_params(request)
        if(not key.isspace()) and (key.isalpha()):
            en_text = vigenere_cipher(text, key)
        else:
            en_text = "Invalid key."
        return HttpResponse(en_text)

def decrypt_vigenere(request):
    if request.method == "POST":
        text, key = get_params(request)
        if(not key.isspace()) and (key.isalpha()):
            en_text = vigenere_cipher_decoder(text, key)
        else:
            en_text = "Invalid key."
        return HttpResponse(en_text)

def encrypt_decrypt_caesar(request):
    if request.method == "POST":
        text, key = get_params(request)
        signal = request.POST['signal']
        if signal == "encrypt":
            if (not key.isspace()) and (not key.isalpha()) and (int(key) >=1 and int(key) <= 26):
                en_text = caesar_cipher(text, int(key))
            else:
                en_text = "Invalid key."
        else:
            if (not key.isspace()) and (not key.isalpha()) and (int(key) >=1 and int(key) <= 26):
                en_text = caesar_cipher(text, -int(key))
            else:
                en_text = "Invalid key."
        return HttpResponse(en_text)    

encryptme/encryption/templates/encryption/caesar.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Encryptme - Caesar{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'encryption/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <body>
        <nav>
            <ul class="nav-links">
                <li style="float: left;">
                    <h1>Caesar</h1>
                </li>
                <div class="sub-links">
                    <li>
                        <a href="{% url 'encryption:index' %}">Encryptme</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vigenere' %}">Vigenere</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vernam' %}">Vernam</a>
                    </li>
                </div>
            </ul>
        </nav>
        {% block body %}
        <div class="row">
            <div class="column">
                <form id="frm-encrypt" class="en_form" autocomplete="off">
                    {% csrf_token %}
                    <input type="text" name="encryptsign" id="encryptsign" value="encrypt" hidden>
                    <input type="text" name="to_encrypt" id="to_encrypt" placeholder="Type your text here" required><br>
                    <input type="text" name="key" id="key" placeholder="Key (1-26)" required><br>
                    <button onclick="myFunction()" type="submit" id="encrypt-btn">Encrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-en">{{ en_text }}</h2>
                </div>
            </div>
            <div class="column">
                <form id="frm-decrypt" class="en_form" autocomplete="off">
                    {% csrf_token %}
                    <input type="text" name="decryptsign" id="decryptsign" value="decrypt" hidden>
                    <input type="text" name="to_decrypt" id="to_decrypt" placeholder="Type your encrypt" required><br>
                    <input type="text" name="dekey" id="dekey" placeholder="Key (1-26)" required><br>
                    <button type="submit" id="decrypt-btn">Decrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-de">{{ en_text }}</h2>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $(document).on('submit', '#frm-encrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:encrypt_decrypt_caesar" %}',
                    data: {
                        to_encrypt: $("#to_encrypt").val(),
                        key: $("#key").val(),
                        signal: $('#encryptsign').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-en').html(data);
                    }
                });
            });
        </script>

        <script type="text/javascript">
            $(document).on('submit', '#frm-decrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:encrypt_decrypt_caesar" %}',
                    data: {
                        to_encrypt: $("#to_decrypt").val(),
                        key: $("#dekey").val(),
                        signal: $('#decryptsign').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-de').html(data);
                    }
                });
            });
        </script>
        <!-- <script>
            function myFunction() {
              var x, text;
            
              // Get the value of the input field with id="numb"
              x = document.getElementById("key").value;
            
              // If x is Not a Number or less than one or greater than 10
              if (isNaN(x) || x < 1 || x > 26) {
                text = "Input not valid";
                alert(text);
              } else {
                text = "Input OK";
                alert(text);
              }
            }
        </script> -->
        {% endblock %}
    </body>
</html>

encryptme/encryption/templates/encryption/index.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Encryption{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'encryption/style.css' %}">
    </head>
    <body>
        <nav>
            <ul class="nav-links">
                <li style="float: left;">
                    <h1>Encryptme</h1>
                </li>
                <div class="sub-links">
                    <li>
                        <a href="{% url 'encryption:caesar' %}">Caesar</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vigenere' %}">Vigenere</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vernam' %}">Vernam</a>
                    </li>
                </div>
            </ul>
        </nav>
        {% block body %}
        <div class="intro">
            <h2>Welcome to Encryptme</h2>
            <p><i>Encryptme</i> is an encryption translator. It is able to translate to and from several ciphers which consists of:</p>
            <ul>
                <li>Caesar Cipher</li>
                <li>Vernam Cipher</li>
                <li>Vigenere Cipher</li>
            </ul>
            <p>Just click on any othe links on top to redirect you to the needed cipher.</p>
        </div>
        {% endblock %}
    </body>
</html>

encryptme/encryption/templates/encryption/vernam.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Encryptme - Vernam{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'encryption/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <body>
        <nav>
            <ul class="nav-links">
                <li style="float: left;">
                    <h1>Vernam</h1>
                </li>
                <div class="sub-links">
                    <li>
                        <a href="{% url 'encryption:caesar' %}">Caesar</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vigenere' %}">Vigenere</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:index' %}">Encryptme</a>
                    </li>
                </div>
            </ul>
        </nav>
        {% block body %}
        <div class="row">
            <div class="column">
                <form id="frm-encrypt" class="en_form">
                    {% csrf_token %}
                    <input type="text" name="to_encrypt" id="to_encrypt" placeholder="Type your text here"><br>
                    <input type="text" name="key" id="key" placeholder="Key (in letters)"><br>
                    <button type="submit" id="encrypt-btn">Encrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-en">{{ en_text }}</h2>
                </div>
            </div>
            <div class="column">
                <form id="frm-decrypt" class="en_form">
                    {% csrf_token %}
                    <input type="text" name="to_decrypt" id="to_decrypt" placeholder="Type your text here"><br>
                    <input type="text" name="dekey" id="dekey" placeholder="Key (in letters)"><br>
                    <button type="submit" id="decrypt-btn">Decrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-de">{{ en_text }}</h2>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $(document).on('submit', '#frm-encrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:encrypt_vernam" %}',
                    data: {
                        to_encrypt: $("#to_encrypt").val(),
                        key: $("#key").val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-en').html(data);
                    }
                });
            });
        </script>
        <script type="text/javascript">
            $(document).on('submit', '#frm-decrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:decrypt_vernam" %}',
                    data: {
                        to_encrypt: $("#to_decrypt").val(),
                        key: $("#dekey").val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-de').html(data);
                    }
                });
            });
        </script>
        {% endblock %}
    </body>
</html>

encryptme/encryption/templates/encryption/vigenere.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Encryptme - Vigenere{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'encryption/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <body>
        <nav>
            <ul class="nav-links">
                <li style="float: left;">
                    <h1>Vigenere</h1>
                </li>
                <div class="sub-links">
                    <li>
                        <a href="{% url 'encryption:caesar' %}">Caesar</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:index' %}">Encryptme</a>
                    </li>
                    <li>
                        <a href="{% url 'encryption:vernam' %}">Vernam</a>
                    </li>
                </div>
            </ul>
        </nav>
        {% block body %}
        <div class="row">
            <div class="column">
                <form id="frm-encrypt" class="en_form">
                    {% csrf_token %}
                    <input type="text" name="to_encrypt" id="to_encrypt" placeholder="Type your text here"><br>
                    <input type="text" name="key" id="key" placeholder="Key (in letters)"><br>
                    <button type="submit" id="encrypt-btn">Encrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-en">{{ en_text }}</h2>
                </div>
            </div>
            <div class="column">
                <form id="frm-decrypt" class="en_form">
                    {% csrf_token %}
                    <input type="text" name="to_decrypt" id="to_decrypt" placeholder="Type your text here"><br>
                    <input type="text" name="dekey" id="dekey" placeholder="Key (in letters)"><br>
                    <button type="submit" id="decrypt-btn">Decrypt</button>
                </form>
                <div class="result">
                    <h2 id="res-de">{{ en_text }}</h2>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $(document).on('submit', '#frm-encrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:encrypt_vigenere" %}',
                    data: {
                        to_encrypt: $("#to_encrypt").val(),
                        key: $("#key").val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-en').html(data);
                    }
                });
            });
        </script>

        <script type="text/javascript">
            $(document).on('submit', '#frm-decrypt', function(e){
                e.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: '{% url "encryption:decrypt_vigenere" %}',
                    data: {
                        to_encrypt: $("#to_decrypt").val(),
                        key: $("#dekey").val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        $('#res-de').html(data);
                    }
                });
            });
        </script>
        {% endblock %}
    </body>
</html>